name: deploy-nightly

on:
  schedule:
    - cron: "23 5 * * *"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build tools
        run: pip install build twine click click-log lxml shapely networkx scipy numpy

      - name: Run prep_nightly script and publish if ready
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          PYTHONPATH: .
        run: |
          echo "Updating version number"
          output=$(python scripts/prep_nightly.py)
          echo "Completed nightly prep"
          echo "Output: $output"
          if [[ $output == *"OK to deploy"* ]]; then
            python -m build --sdist
            twine upload dist/*
            echo "Published to pypi.org"
          fi
