name: tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: |
        pip install shapely lxml click networkx scipy numpy click-log pytest
    - name: Run Tests (Python backend)
      env:
        PREFIGURE_USE_PYTHON: "1"
        PYTHONPATH: .
      run: pytest -vv
